const express = require('express');
const router = express.Router();
const homeController = require('../controllers/homeController');
const authController = require('../controllers/authController');
const dashboardController = require('../controllers/dashboardController');
const venueController = require('../controllers/venueController');
const eventController = require('../controllers/eventController');
const artistController = require('../controllers/artistController');
const ticketCategoryController = require('../controllers/ticketCategoryController');
const ticketController = require('../controllers/ticketController');
const orderController = require('../controllers/orderController');
const seatController = require('../controllers/seatController');
router.get('/', homeController.index);
router.get('/register', authController.renderRegister);
router.get('/register/customer', authController.renderRegisterCustomer);
router.get('/register/organizer', authController.renderRegisterOrganizer);
router.get('/register/admin', authController.renderRegisterAdmin);
router.post('/login', authController.login);
router.post('/register/customer', authController.registerCustomer);
router.post('/register/organizer', authController.registerOrganizer);
router.post('/register/admin', authController.registerAdmin);
router.get('/logout', authController.logout);
router.get(['/dashboard', '/customer/dashboard'], dashboardController.customerDashboard);
router.get('/admin', dashboardController.adminDashboard);
router.get('/organizer/dashboard', dashboardController.organizerDashboard);
router.get('/profile', dashboardController.profile);
router.get('/organizer/profile', dashboardController.organizerProfile);
router.get('/admin/profile', dashboardController.adminProfile);
router.post('/profile/update', dashboardController.updateProfile);
router.post('/profile/change-password', dashboardController.changePassword);
router.get('/admin/venues', venueController.adminVenues);
router.get('/organizer/venues', venueController.organizerVenues);
router.get('/customer/venues', venueController.customerVenues);
router.post('/api/venues', venueController.createVenue);
router.put('/api/venues/:id', venueController.updateVenue);
router.delete('/api/venues/:id', venueController.deleteVenue);
router.get('/events', eventController.customerEvents);
router.get('/organizer/events', eventController.organizerEvents);
router.get('/admin/events', eventController.adminEvents);
router.post('/api/events', eventController.createEvent);
router.put('/api/events/:id', eventController.updateEvent);
router.delete('/api/events/:id', eventController.deleteEvent);
router.get('/admin/artists', artistController.adminArtists);
router.get('/customer/artists', artistController.customerArtists);
router.get('/organizer/artists', artistController.organizerArtists);
router.post('/api/artists', artistController.createArtist);
router.put('/api/artists/:id', artistController.updateArtist);
router.delete('/api/artists/:id', artistController.deleteArtist);
router.get('/admin/ticket-categories', ticketCategoryController.adminTicketCategories);
router.get('/organizer/ticket-categories', ticketCategoryController.organizerTicketCategories);
router.get('/customer/ticket-categories', ticketCategoryController.customerTicketCategories);
router.post('/api/ticket-categories', ticketCategoryController.createCategory);
router.put('/api/ticket-categories/:id', ticketCategoryController.updateCategory);
router.delete('/api/ticket-categories/:id', ticketCategoryController.deleteCategory);
router.get('/admin/tickets', ticketController.adminTickets);
router.get('/organizer/tickets', ticketController.organizerTickets);
router.delete('/api/tickets/:id', ticketController.deleteTicket);
router.put('/api/tickets/:id', ticketController.updateTicket);
router.get('/my-tickets', ticketController.myTickets);
router.get('/events/:eventId/seats', ticketController.seats);
router.get('/api/tickets/orders', ticketController.getOrdersForTicket);
router.get('/api/tickets/event-details/:eventId', ticketController.getEventTicketDetails);
router.post('/api/tickets', ticketController.createTicket);
router.get('/orders', orderController.listOrders);
router.put('/api/orders/:id/status', orderController.updateStatus);
router.delete('/api/orders/:id', orderController.deleteOrder);
router.get('/checkout/:eventId', orderController.checkout);
router.post('/api/checkout/validate-promo', orderController.validatePromo);
router.post('/api/checkout/process', orderController.processCheckout);
router.get('/admin/orders', orderController.adminOrders);
router.get('/admin/promotions', (req, res) => {
  const username = req.query.username || 'admin';
  res.redirect(`/promotions?username=${encodeURIComponent(username)}`);
});
router.get('/promotions', orderController.listPromotions);
router.post('/api/promotions', orderController.createPromotion);
router.put('/api/promotions/:id', orderController.updatePromotion);
router.delete('/api/promotions/:id', orderController.deletePromotion);
router.get('/seats', seatController.listSeats);
router.post('/api/seats', seatController.createSeat);
router.put('/api/seats/:id', seatController.updateSeat);
router.delete('/api/seats/:id', seatController.deleteSeat);
module.exports = router;
